export enum PreferredLocation {
    PREFERRED_LOCATION_UNDEFINED,
    PREFERRED_LOCATION_NO_MATTER,
    PREFERRED_LOCATION_SHADOW,
    PREFERRED_LOCATION_SHADOW_TO_HALF_SHADOWS,
    PREFERRED_LOCATION_HALF_SHADOWS,
    PREFERRED_LOCATION_HALF_SHADOWS_TO_SUNNY,
    PREFERRED_LOCATION_SUNNY,
}