name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Project-Env/project-env-github-action@v1.4.0
      - run: |
          npm ci
      - if: github.ref == 'refs/heads/main'
        run: |
          npx expo-cli publish --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
